# Setup
title: ""
tagline: ""
description: ""
baseurl: "/dsc180-website" # Keep this for GitHub Pages
url: "https://okinahiru.github.io"
permalink: pretty

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y
